### ISSUE TITLE
Error: ReferenceError: module is not defined. (using jspm 0.17)

### ISSUE THREAD

**Issue by PacciniBruno** [systemjs/plugin-json#6]
I'm having trouble using the plugin-json with jspm@0.17.

using: `return 'export default ' + JSON.stringify(JSON.parse(load.source)) + ';';`
instead of `module.exports` in the `translate` hook solves that issue for me.

Am I missing something or is that a bug ?

**Comment by guybedford** [comment]
The only reason this might be happening is if you're setting `format: 'esm'` say for your package, then it will try to load plugins as esm format as well, while the plugin is actually relying on the CommonJS format.

I've pushed out a 0.1.1 that sets the format to ensure this is avoided.

You can also use `format: 'json'` metadata in jspm 0.17 like:

``` javascript
System.config({
  meta: {
    '*.json': {
      format: 'json'
    }
  }
});
```

As an alternative to installing the plugin.

**Comment by PacciniBruno** [comment]
Thank you for answering so quickly.

Unfortunately that didn't solve it for me. I then have a syntax error, as we don't do anything if `this.builder` is undefined, in the translate hook. It looks like systemJS is trying to load my JSON file as a javascript esm module, without wrapping it in `module.export`, or anything. 

Also

``` js
System.config({
  meta: {
    '*.json': {
      format: 'json'
    }
  }
});
```

Seemed to be completely ignored. I have

```
  meta: {
    "**/*.html": {
      "loader": "text"
    },
    "**/*.json": {
      "loader": "json",
      "format": "json"
    },
    "**/*.css": {
      "loader": "css"
    }
  },
```

in my jspm.config.js file, but I want it to be applied to jspm packages I load, so I wondered if I should add the meta config for every package that use the json plugin, like this:

``` js
packages: {
    "myOwnJspmPackageInstalledFromGithub@master": {
      "map": {
        ...
      },
      meta: {
         "**/*.html": {
            "loader": "text"
          },
          "**/*.json": {
            "loader": "json",
            "format": "json"
          },
          "**/*.css": {
            "loader": "css"
          }
    },
}
```

That seems like a pain though, and prevents reproducible installs, since as far as I understand, this meta config cannot come from package.json overrides ?

I'm sorry if I don't make sense at all, but I'm having a really hard time wrapping my head around the jspm ecosystem, subtle changes between 0.16.x and 0.17, especially the way extensions are handled.

In the meantime, forking and using a plugin-text like approach, using export default and an additional `JSON.parse` call in the translate hook works for me for now:

``` js
load.metadata.format = 'esm';
return 'export default ' + JSON.stringify(JSON.parse(load.source)) + ';';
```

**Comment by guybedford** [comment]
I definitely tested this to work in jspm 0.17. There was a build bug I also caught here in https://github.com/systemjs/systemjs/commit/9f5690383489422314f984531bf8242123a899eb which may be the other issue (the build was stalling without this). Perhaps that was the other error you had? This will be released in the next SystemJS version. Note that `**/*` is not supported in SystemJS meta. The package.json does support meta configuration in jspm 0.17 as well.

**Comment by PacciniBruno** [comment]
Ah, very good, that worked ! I assumed wrongly that the glob syntax would work.
Thanks a lot for your help
